### ISSUE TITLE
redirect outside of angular

### ISSUE THREAD

**Issue by chriseugenerodriguez** [uma075/msalb2c-demo#2]
Hi,

I know you have to redirect route outside of angular to prevent double login. I have tried this and it works, but I am getting issue when deploying this in production, because its SPA. And callback breaks because it isn't loaded from route to initialize SPA. So I ask if you have example with redirect html that initializes callback to SPA.

**Comment by uma075** [comment]
On redirection after login, B2C API store token into storage(Session/local based on user's choice). You can use Authentication Guard to handle this redirection. You can see this.
https://github.com/uma075/msalb2c-demo/blob/master/src/app/authentication/authentication.guard.ts
